Refactor to use yarn workspaces
romzamir/jaborom-application pull request #1
Opened 2022-10-17 20:25 UTC by Salenia

Co-authored-by: romzamir <romzamir@users.noreply.github.com>

2022-10-17 21:19 UTC, romzamir commented
.prettierrc file should be in the main dir

2022-10-17 21:21 UTC, romzamir requested changes

2022-10-17 21:21 UTC, romzamir commented on .gitignore
> +.vscode
Why ignore vscode directory? We have the spell checker words there and should have launch scripts in there. They should be used by everyone with the same values

2022-10-17 21:21 UTC, romzamir commented on .gitignore
> +*.lock
Shouldn't yarn.lock be in the git?

2022-10-17 21:21 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +        public dateOfBirth: Date | null,
Dates can be strings when they were fetched from the backend.

2022-10-17 21:21 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +    constructor(
Did you change the usages of the constructor to pass the values instead of the template?

2022-10-17 21:48 UTC, Salenia commented on .gitignore
> +.vscode
this is optional but the idea behind it was that the new developer does not have to use vscode as his text editor and can use what ever tool s/he what to use
we can add tool specific config files such as `.prettierc` etc

2022-10-17 21:50 UTC, Salenia commented on .gitignore
> +*.lock
yeah but as I mentioned previously, on your system you might want to use `npm` or `pnpm`, this does not have any effect on the end product so I as a maintainer don't care what software you want to use nor should I

2022-10-17 21:51 UTC, Salenia commented on apps/web/client/src/core/models/profile.ts
> +        public dateOfBirth: Date | null,
The `Date` object can receive as ctor param either `string` or `Date`, thus creating a new `Date` object representing the same date, I will modify It so it could be either

2022-10-17 21:52 UTC, Salenia commented on apps/web/client/src/core/models/profile.ts
> +    constructor(
No, on it

2022-10-17 22:05 UTC, romzamir commented on .gitignore
> +.vscode
Yeah, I know. But why not share the launch configs? Every developer that uses vscode will have the launch configuration easily

2022-10-17 22:09 UTC, romzamir commented on .gitignore
> +*.lock
This DOES have an effect on the end product. It makes sure that when installing the package's dependencies you will get the exact same packages versions.

For example, if you set express@^1.0.0 as a dependency and you run `npm install` you will get express@1.2.0. And package-lock's job is to make sure that the version that was installed is the version that will always be installed unless you explicitly upgraded that

2022-10-17 22:14 UTC, romzamir requested changes

2022-10-17 22:14 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +    private static formatDate(maybeDate: Date | string | null): Date | null {
Should be in date utils

2022-10-17 22:14 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +import {uuidv4} from '@firebase/util';
I prefer using the uuid package instead of using firebase as a dependency to this model

2022-10-17 22:14 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +    public static default() {
`public static get empty() {`
This is to simply do `Profile.empty` instead of `Profile.empty()`

2022-10-17 22:14 UTC, romzamir commented on apps/web/client/src/core/models/profile.ts
> +            randomInt(Number.MAX_VALUE),
I'd should be null when there is no id

2022-10-19 03:35 UTC, Salenia commented on .gitignore
> +*.lock
alright I'm on it

2022-10-22 18:59 UTC, romzamir approved these changes

2022-10-22 19:00 UTC, merged